--- 
apiVersion: v1


kind: Pod

metadata: 
  labels: 
    type: datbase
    tier: db-tier 
  name: postgress 

spec: 
  containers: 
    -  image: postgres
       name: postgres
       env:
         - name: POSTGRES_PASSWORD
           value: myscretpassword 

