--- 
apiVersion: v1


kind: Service 

metadata: 
   name: myapp-services

spec: 
   type: NodePort
   ports:
     - targetPort: 80
       port: 80
       nodePort: 30008
  
   selector:
       apps: my-app
       type: front-end


