--- 
apiVersion: v1


kind: Service 

metadata:
  name: redis-service 
  labels: 
    name: redis-service  
    app: demo-redis-service 

spec: 
  ports:
    - port: 6379
      targetPort: 6379
  selector:
     name: redis-app-pod
     app: demo-redis-app
