--- 
apiVersion: v1


kind: Pod

metadata:
  name: redis-app-pod 
  labels: 
    name: redis-app-pod  
    app: demo-redis-app 

spec: 
  containers: 
    -  image: redis 
       name: redis 
       ports:
         - containerPort: 6379 

