--- 
apiVersion: v1


kind: Pod

metadata:
  name: result-app-pod 
  labels: 
    name: result-app-pod  
    app: demo-result-app 

spec: 
  containers: 
    -  image: dockersamples/examplevotingapp_result 
       name: result-app
       ports:
         - containerPort: 80

